### ISSUE TITLE
Splite the huge Docker Compose into multiple files

### ISSUE THREAD

**Issue by Lowpoc** [AntonioFalcaoJr/EDA.CleanArch.DDD.CQRS.EventSourcing#437]
**Is your feature request related to a problem? Please describe.**
The considerable file for docker-compose.yml break the single responsibility principle

**Describe the solution you'd like**
I suggest creating multiples files for docker-compose

![image](https://user-images.githubusercontent.com/17841549/206611077-f0f507d3-e85e-4740-a98e-eb136840298f.png)

Executing a new strategy is simple:

``` yml

docker-compose -f docker-compose.db.yml \
  -f docker-compose.api-services.yml \
  -f docker-compose.backend.yml \
  -f docker-compose.frontend.yml \
  -f docker-compose.gateway.yml \
  up -d`
```

**Comment by AntonioFalcaoJr** [comment]
**Development:**
docker-compose.Infrastructure.Development

**Staging** (_Health check dependency must be kept through Docker DNS_)
docker-compose.Infrastructure.Staging
docker-compose.Services.Staging

**Comment by AntonioFalcaoJr** [comment]
https://github.com/AntonioFalcaoJr/EDA.CleanArch.DDD.CQRS.EventSourcing/pull/486
